beyond-sw-camp/be12-fin-Catcher-GrapeField-FE

src/admin/Detail.vue, src/admin/List.vue, src/admin/Report.vue, src/common/Footer.vue, src/common/Header.vue, src/common/Sidebar.vue, src/events/Detail.vue, src/events/EventHeader.vue, src/events/List.vue, src/events/Review.vue, src/events/post/Comment.vue, src/events/post/Detail.vue, src/events/post/List.vue, src/events/post/Register.vue, src/user/Longin.vue, src/user/Signup.vue, src/user/UserInfo.vue
=> [init] 패키지 구조 설정

src/router/index.js, src/stores/user.js, src/user/Login.vue, src/user/Longin.vue
#8 로그인 페이지 구현
소셜로그인 버튼을 포함한 로그인 페이지 구현
어떤 변경 사항이 있나요?
=> feat: 로그인 페이지 구현 (#8)

src/App.vue, src/common/Footer.vue, src/common/Header.vue
#15 
Header, Footer CSS 수정
어떤 변경 사항이 있나요?
=> #15 Header, Footer CSS 수정

src/router/index.js, src/user/Signup.vue, src/user/SignupSuccess.vue
#26 회원가입 성공 페이지 구현
회원가입 성공 시 페이지 구현(로그인 페이지로 이동 가능)
어떤 변경 사항이 있나요?
간격이나  위치가 안맞는 것은 추후 수정
=> feat: 회원가입 성공 페이지 구현 (#26)

src/assets/data/category.json, src/main/Category.vue, src/main/Main.vue
#25
카테고리 구현
어떤 변경 사항이 있나요?
한 번에 레이아웃 설정하기로 했기에 좌우 정렬은 고려하지 않았습니다.
=> #25 카테고리 구현

src/events/EventShowMore.vue, src/router/index.js
Closes #51 메인페이지의 카드 템플릿 활용
메인페이지의 카드 템플릿 활용
어떤 변경 사항이 있나요?
=> 메인페이지 카드, 카테고리  활용

src/main/Calendar.vue, src/main/Main.vue
=> #47 반응형으로 달력 구현

src/events/EventShowMoreCard.vue, src/events/EventShowMoreList.vue
#59 상세정보로 넘어가는 링크 수정
v-for문 부분의 코드 수정
어떤 변경 사항이 있나요?
현재는 events의 id값으로 해놨는데 추후에 어떤식으로 변경하면 될지 의논하면 될 것 같습니다
=> feat: 공연/전시 페이지 하단 카드 링크 수정 (#59)

src/main/CardList.vue, src/main/Main.vue
#57 
공통적으로 사용될 카드 리스트 구현
- 현재는 메인페이지의 오픈/종료 예정에 적용
어떤 변경 사항이 있나요?
=> #57 카드 리스트 구현

src/events/EventDetailTab.vue
#67 상세 정보의 탭  순서 변경
상세 정보와 추천 탭의 위치를 변경
어떤 변경 사항이 있나요?
=> feat: 공연/전시의 상세페이지 탭 오타 수정

Dockerfile, nginx/default.conf
배포 편하게 하기 위해서 Dockerfile 작성
#74 
배포 편리를 위해 Dockerfile 추가
어떤 변경 사항이 있나요?
=> [ADD] Dockerfile

src/App.vue, src/assets/data/chat.json, src/common/Sidebar.vue, src/events/chat/Detail.vue, src/events/chat/List.vue, src/router/index.js
#79 
- 사이드바에서 채팅방으로 이동 가능
- 전체 채팅 목록, 채팅방 구현현
어떤 변경 사항이 있나요?
App.vue에서 스타일 변경했습니다
=> # 79 채팅 구현

src/calendar/CalendarGrid.vue, src/calendar/CalendarHeader.vue, src/calendar/CalendarLegend.vue, src/calendar/DetailCalendar.vue, src/router/index.js
#87 캘린더 레이아웃 구현
캘린더 레이아웃 구현, 좌 우 버튼으로 월 이동 가능
어떤 변경 사항이 있나요?
=> feat: 캘린더 레이아웃 구현 (#87)

src/user/mypage/PasswordChange.vue, src/user/mypage/UserInfo.vue, src/user/mypage/Withdraw.vue
#83 
회원 정보 페이지에서 내 정보 보기 페이지 수정(회원 정보 변경과 비밀번호 변경 분리)
회원탈퇴 기능 추가
어떤 변경 사항이 있나요?
=> [fix]회원 정보 페이지 일부 수정, 탈퇴 기능 추가

src/common/Header.vue, src/stores/useUserStore.js, src/user/Login.vue
#1 
로그인 관련 userUserStore 일부 수정, Header에 로그인 반영
어떤 변경 사항이 있나요?
=> [fix] 로그인 수정, header 반영

src/common/Header.vue
#1 
검색바 실수로 지운 거 다시 구현
어떤 변경 사항이 있나요?
=> [fix] 검색바 되살림

src/calendar/BookingInfoSection.vue
#111 오타수정
전체캘린더와 마이페이지 캘린더 랜더링 과정에서 오타 수정
어떤 변경 사항이 있나요?
=> feat: 캘린더 부분 오타 수정(#111)

src/events/Register.vue, src/events/community/Community.vue, src/events/community/RightSide.vue, src/router/index.js, src/stores/useUserStore.js
#116 
커뮤니티 페이지 홈 및 rightside 추가
어떤 변경 사항이 있나요?
=> [feat] communiyPage 추가

index.html, src/main/TopBanner.vue
#122 
- 각 배너에 맞는 링크 연결
- 폰트 변경
- 너비는 70vw 로 변경
- 상단 배너에서 바로 검색 가능
어떤 변경 사항이 있나요?
나중에 링크가 수정할 예정입니다
=> #122 상단 배너 변경

src/user/mypage/AddSchedule.vue, src/user/mypage/MyCalendar.vue
#126 마이페이지 캘린더 일정등록 구현
마이페이지 캘린더 일정등록 구현
어떤 변경 사항이 있나요?
=> feat: 마이페이지 캘린더 일정등록 구현(#126)

src/main/TopBanner.vue
=> #122 배너 길이 조정

src/App.vue, src/admin/Admin.vue, src/router/index.js, src/user/mypage/MyPage.vue, src/user/mypage/QnA.vue
페이지 전체 margin에 따른 밀림 문제 해결 및 자체적으로 header, footer 추가
#134 
마이페이지, 관리자 페이지 사이드바 밀림 수정, 헤더 푸터 추가
어떤 변경 사항이 있나요?
=> [fix] admin, mypage 사이드바

src/events/EventPost.vue
#137
- 상세페이지 게시판 디자인 변경
- 게시판 필터링 기능 추가
- 게시판 페이지네이션
어떤 변경 사항이 있나요?
향후에 전체 레이아웃 틀 조정 해야함 (중복 마진 같은 것)
=> [Feat] 상세페이지 게시판 페이지 디자인 변경 및 기능 추가

src/main/Main.vue, src/main/PopularChatRoom.vue, src/main/PopularPost.vue
#139
인기 게시글/채팅방 사이즈 수정
어떤 변경 사항이 있나요?
=> #139 인기 게시글/채팅방 사이즈 수정

src/App.vue, src/admin/customercenter/CustomerCenter.vue, src/calendar/CalendarGrid.vue, src/calendar/CalendarHeader.vue, src/calendar/CalendarLegend.vue
나중에 필터링하기 편하도록 Legend를 버튼으로 수정(다중선택 가능)
#94 
캘린더 버튼 카테고리화
어떤 변경 사항이 있나요?
=> [fix] 캘린더 카테고리 버튼으로 수정

src/common/Header.vue
#41
-화면 줄였을 때 로그인/로그아웃 잘리거나 줄 바뀌지 않도록 함
어떤 변경 사항이 있나요?
=> [Design] 헤더 로그인/비로그인 줄바뀌지 않도록 조정

src/main/Category.vue
#128
- 우선, 사이즈만 수정
어떤 변경 사항이 있나요?
- 링크는 추후에 연결 예정
=> #128 카테고리 수정

src/main/TopBanner.vue
=> #139 배너 길이 수정

src/events/EventShowMore.vue
#147 제일 상단의 추천 카드 부분에 여백
제일 상단의 추천 카드 부분에 여백
어떤 변경 사항이 있나요?
=> feat: 제일 상단의 추천 카드 부분에 여백 (#147)

src/App.vue
=> [fix] App.vue margin 제거

src/admin/customercenter/CustomerCenter.vue, src/admin/customercenter/CustomerCenterBottom.vue, src/admin/customercenter/CustomerCenterHeader.vue, src/admin/customercenter/Faq.vue, src/admin/customercenter/Guide.vue, src/admin/customercenter/NoticeList.vue, src/admin/customercenter/Qna.vue, src/admin/customercenter/RequestList.vue, src/admin/customercenter/Search.vue, src/assets/data/popular-post.json, src/main/Main.vue, src/main/PopularChatRoom.vue, src/main/PopularPost.vue
#142 #155
- 고객센터 레이아웃 프레임 조정
- 메인페이지 추천게시판, 인기채팅방 프레임 조정
- 추천게시판 목록 레이아웃 틀 재설정
어떤 변경 사항이 있나요?
- flex display 위주로 했습니다.
=> [Design] Main.vue에서 PopulatChatRoom, PopularPost 레이아웃 조정

src/main/Calendar.vue
#160
달력 관련 요소들 사이즈 및 폰트를 전반적으로 줄임.
반응형
어떤 변경 사항이 있나요?
=> #160 달력 수정

src/main/CardList.vue, src/main/Main.vue
#132
메인 카드리스트 레이아웃 수정 및 더미 데이터 연결
어떤 변경 사항이 있나요?
=> #132 메인 카드리스트 수정

src/common/Header.vue, src/common/Sidebar.vue
Header에서 mypage 연결 및 사이드 일부 수정(추후 이어서 수정할 필요 있음)
#85 
헤더에서 ...을 누르고 설정 누르면 마이페이지로 이동하도록 수정
어떤 변경 사항이 있나요?
=> [fix] Header에서 mypage 연결

src/events/EventShowMoreCard.vue
#49
- 이벤트카드 간격이 바뀌어 있어서 수정
어떤 변경 사항이 있나요?
간격 나중에도 원하는대로 바꿀 수 있음
=> [design] 상세페이지 카드 간격 오류 수정

src/admin/customercenter/CustomerCenter.vue
#142
-좌우여백 추가
어떤 변경 사항이 있나요?
단순히 여백만 추가했어요 ~
=> [design] 고객센터 페이지 좌우 여백 추가

Dockerfile, src/App.vue, src/calendar/DetailCalendar.vue
#74 
build를 따로 해야했던 이전 버전에서 build까지 함께 되도록 수정 및 파일 내 자잘한 오타 수정
어떤 변경 사항이 있나요?
=> [fix] Docerkfile 수정

src/stores/useUserStore.js
#186 
유저 정보를 편히 다루기 위해 쿠키에서 받아온 유저의 정보를 세션에 저장하도록 수정
어떤 변경 사항이 있나요?
=> [fix] 로그인 관련 일부 수정

src/main/Calendar.vue, src/stores/uesCalendarStore.js
#188 
메인 페이지에서 이벤트를 예매일 시작일과 마지막일 기준으로 표시하려는데 아직 TicketInfo가 null이라서
받아오는 정보가 없어 추후 수정 필요
어떤 변경 사항이 있나요?
=> [Feat/events/list/calendar] 메인 페이지 캘린더 표시

src/events/EventShowMoreList.vue
#192 
글자만 조회되고 이미지는 아직 안 됨
어떤 변경 사항이 있나요?
다음 기능 구현 때는 이미지 조회도 가능하게 할 거예요~
=> #192 공연 전시 목록 간단 조회

package-lock.json, package.json, src/events/chat/Detail.vue, src/utils/webSocketClient.js, vite.config.js
#197 #198
sockjs-client + stompjs 라이브러리 패키지 설정
Detail.vue 에 STOMP 연결추가
어떤 변경 사항이 있나요?
=> [feat] 웹소켓 연결

.env, .gitignore, src/utils/webSocketClient.js, vite.config.js
#197
- "/ws" 엔드포인트 상대경로 설정하기
어떤 변경 사항이 있나요?
=> [chore] 웹소켓 연결경로 환경변수처리

src/events/Event.vue, src/events/EventDetail.vue, src/events/EventHeaderInfo.vue, src/events/EventShowMoreList.vue, src/events/post/EventPost.vue, src/events/post/PostDetail.vue, src/events/post/PostRegister.vue, src/main/Card.vue, src/router/index.js, src/stores/useEventsStore.js, src/stores/usePostStore.js
#204 
게시글 등록 페이지 만들고 백엔드와 연동하여 게시글을 등록하도록 기능 추가
게시글을 등록하면 등록된 게시글 페이지로 라우팅 설정
어떤 변경 사항이 있나요?
=> [Feat/events/post/register] 게시글 등록

src/events/post/Comment.vue, src/events/post/CommentList.vue, src/events/post/CommentRegister.vue, src/events/post/EventPost.vue, src/events/post/PostDetail.vue, src/events/post/PostRegister.vue, src/stores/useCommentStore.js
#206 
댓글 목록을 불러오고 댓글을 등록하기 기능 추가, 댓글을 새로 등록할 경우 기존 목록에서 추가된 댓글까지 포함하여 표시
어떤 변경 사항이 있나요?
=> [feat] 댓글 목록 불러오기, 댓글 등록하기

src/user/mypage/UserInfo.vue
#221
마이페이지 개인정보 수정
어떤 변경 사항이 있나요?
=> #221 마이페이지 개인정보 수정

src/main/Calendar.vue
#224
- 데이터 연결
- 상세 페이지로 이동도 가능
어떤 변경 사항이 있나요?
=> #224 메인 캘런더에 데이터 연결

src/common/Header.vue, src/events/post/EventPost.vue, src/main.js, src/stores/useUserStore.js, src/utils/axios.js
#187 
RTOKEN을 추가해서 redis에서 로그인 시간 관리하면서 토큰 재발행 설정 추가, axios 설정 변경
어떤 변경 사항이 있나요?
=> [fix] RTOKEN추가, 토큰 갱신

src/events/chat/List.vue, src/stores/useChatRoomsListStore.js
#232 common/chat/List.vue 채팅방 리스트 불러오기
채팅방 리스트 백엔드와 연결
어떤 변경 사항이 있나요?
에러 나는 부분 생기면 공유해주세요~
=> [#232] common/chat/List.vue 채팅방 리스트 불러오기

src/events/chat/Detail.vue, src/stores/useChatRoomStore.js
#237
스크롤기능 약간 수정
piniaStore로 API 호출
하이라이트 기능 등 스냅샷
어떤 변경 사항이 있나요?
=> Feat/chatroom/detail PiniaStore로 변경 & 스크롤기능

src/common/Sidebar.vue, src/events/chat/Detail.vue, src/events/chat/List.vue, src/stores/useChatRoomsListStore.js, src/stores/useChatStore.js
#246 채팅방 입장 퇴장 시 로직 추가, 수정
채팅방 입장 퇴장 시 로직 추가, 수정
어떤 변경 사항이 있나요?
오류나면 꼭 알려주세요~ Props 함수 부분 제거했습니다
=> [#246] 채팅방 입장, 퇴장 로직 추가, 수정

src/events/chat/Detail.vue, src/stores/useChatStore.js
#248 입장, 퇴장 에러 수정
입장, 퇴장 에러 수정
어떤 변경 사항이 있나요?
=> [#248] 입장,퇴장 에러 수정

src/events/chat/Detail.vue, src/stores/useChatRoomStore.js, src/utils/webSocketClient.js
#250
토큰 뽑아오는 위치 변경
어떤 변경 사항이 있나요?
=> [fix] 오류 수정 - 토큰 뽑아오는 위치 변경

src/common/Sidebar.vue, src/stores/useChatRoomStore.js, src/utils/webSocketClient.js
#209 #214
#255 풀리퀘에서 커밋이 누락되어있어 포함하고 다시 올립니다.!!
- Sidebar.vue의 채팅 상세보기 패널에 piniastore.js 에서 백엔드 컨트롤러 + 웹소켓 컨트롤러로 교체
- 메세지 송수신 publish / subscribe 기능 테스트 완료 
- 레이아웃 깨지는 문제 임시 해결
어떤 변경 사항이 있나요?
채팅방에 새로운 메세지 입력영역 칸이 부족하여 레이아웃에 수정이 필요했습니다. 배율로 깨지는 부분은 임시로 수정하였으므로 추후에 다른 분들이 수정해주셔도 무방합니다.
=> [feat/sidebar/chat/detail] (누락된 커밋 포함) 사이드바 채팅패널 채팅메세지 송수신 기능 + 디자인 레이아웃

src/events/chat/Detail.vue, src/stores/useChatRoomStore.js
#262 웹소켓으로 하트 누르기 로직
웹소켓으로 하트 누르기 로직
어떤 변경 사항이 있나요?
=> fix: 웹소켓으로 하트 누르기 로직 #262

src/events/chat/Detail.vue
#260
필요없는 token 파라미터 삭제
어떤 변경 사항이 있나요?
=> [refactor] 파라미터 token 삭제

src/events/chat/Detail.vue
#260
- 병합과정에서 놓친, 오류 발생시키는 중복 메서드 삭제
어떤 변경 사항이 있나요?
=> [fix] 중복 메서드 삭제

src/common/Sidebar.vue, src/events/chat/Detail.vue, src/stores/useChatRoomStore.js
#268
Detail.vue 상태변수 대부분을 piniaStore.js로 옮기기
어떤 변경 사항이 있나요?
=> [feat] piniaStore로 상태 완전 분리 & 하트 기능 오류 수정

src/events/community/LeftSide.vue
#271
인기, 최신 게시글 조회
어떤 변경 사항이 있나요?
=> #271 인기, 최신 게시글 조회

src/events/community/LeftSide.vue
#271
인기 및 최신 게시글 목록 내 게시글 선택 시 공연 내 게시글 탭으로 바로 이동
날짜 형식 변경
CSS 변경
어떤 변경 사항이 있나요?
=> #271 게시글 탭 이동 및 css 수정

src/events/chat/List.vue, src/stores/useChatRoomListStore.js
#274 채팅방 리스트에서 공연, 전시 탭을 인기 채팅방 목록으로 변경
채팅방 리스트에서 공연, 전시 탭을 인기 채팅방 목록으로 변경
어떤 변경 사항이 있나요?
=> [#274] 채팅방 리스트에서 공연, 전시 탭 -> 인기 채팅방으로 변경 로직

src/calendar/BookingInfoSection.vue, src/calendar/CalendarGrid.vue, src/calendar/CalendarHeader.vue, src/calendar/DetailCalendar.vue, src/main/Calendar.vue, src/stores/useCalendarStore.js
#275
캘린더 카테고리 필터링
어떤 변경 사항이 있나요?
=> #275 캘린더 카테고리 필터링

src/events/chat/Detail.vue
#280 퇴장 버튼 디자인 수정
퇴장 버튼 디자인 수정
어떤 변경 사항이 있나요?
=> [#280] 퇴장 버튼 디자인 수정

src/events/EventShowMore.vue, src/events/EventShowMoreCard.vue, src/events/EventShowMoreList.vue, src/events/TypeEventList.vue, src/events/post/CommentList.vue, src/events/review/EventReviewRegister.vue, src/main/CardList.vue, src/main/Main.vue
#288
- 데이터 넣기
- CSS 수정
- 코드 리팩토링
어떤 변경 사항이 있나요?
=> #288 메인 페이지 내 오픈, 종료 예정 카드 수정

src/common/GlobalLoading.vue, src/common/Header.vue, src/main.js, src/main/Calendar.vue, src/main/Main.vue, src/stores/useUserStore.js, src/utils/webSocketClient.js, src/utils/webSocketClient_notify.js, vite.config.js
채팅 웹소켓과 알림 웹소켓 분리
어떤 변경 사항이 있나요?
=> [fix] 웹소켓 분리

src/events/chat/Detail.vue, src/events/chat/List.vue, src/stores/useChatRoomStore.js
#296
채팅 하이라이트 실시간으로 사용자들에게 알리는 로직
어떤 변경 사항이 있나요?
=> [#296] 채팅 하이라이트 실시간으로 사용자들에게 알리기 로직

src/common/Sidebar.vue
#301
로그인 안한 상태에서 내 채팅방 목록 불러오기 에러 수정
어떤 변경 사항이 있나요?
다들 메인페이지에서 http proxy error: /chat/list/my-rooms 요청 에러 안나는지 확인 부탁드립니다~~
=> [#301] 로그인 안한 상태에서 내 채팅방 목록 불러오기 에러 수정

src/user/mypage/contents/Posts.vue
=> #298 uri 변경

src/user/mypage/contents/Comments.vue
=> #299 마이페이지 작성 댓글 데이터 삽입

src/user/mypage/contents/Reviews.vue
#304
마이페이지의 한줄평에 데이터 삽입
어떤 변경 사항이 있나요?
=> #304 마이페이지_한줄평 관리

src/common/Header.vue, src/common/Sidebar.vue, src/events/chat/Detail.vue, src/stores/useChatRoomStore.js
#270 
- 채팅방 스크롤 함수 개선
- 로그인 상태에 맞게 알림 구독 웹소켓 연결하도록 함 (연결 끊어짐 오류 개선)
- 주석들 조금씩 제거함
어떤 변경 사항이 있나요?
=> fix/header/ws 웹소켓 로직 개선 & store 함수 개선

src/events/chat/List.vue, src/stores/useChatRoomListStore.js
#314 
채팅방 목록 공연, 전시 추가
어떤 변경 사항이 있나요?
=> [#314] 채팅방 목록 공연, 전시 추가

src/events/chat/Detail.vue, src/router/index.js
#270
반응형 디자인 수정
어떤 변경 사항이 있나요?
=> [fix] 반응형 디자인 수정

src/common/Header.vue, src/common/Sidebar.vue, src/events/Event.vue, src/search/PostList.vue, src/stores/useEventsStore.js, src/stores/usePostStore.js
공연/전시 히스토리, 캘린더
어떤 변경 사항이 있나요?
=> [Feat/sidebar] 사이드바 일부 기능 추가

Jenkinsfile, k8s/frontend-deployment.yml
=> [feat] jenkinsfile, deployment.yml

Jenkinsfile
=> [#325] 젠킨스 파일 수정

Jenkinsfile
=> jenkins파일 수정

src/utils/socketService.js, src/utils/webSocketClient.js, src/utils/webSocketClient_notify.js
=> [fix] 웹소켓 연결 url 수정, 개발/배포 환경 표시 콘솔에 추가

src/events/chat/Detail.vue
#334
하이라이트 시간 포맷함수 변경 및 하이라이트 접어두기 기능 추가
어떤 변경 사항이 있나요?
=> [feat] 하이라이트 타임포맷 변경 및 토글키 생성

src/events/TypeEventList.vue, src/main/Main.vue
#337
- 링크, title
어떤 변경 사항이 있나요?
=> #337 오픈/종료 예정 수정

src/assets/data/banner-slides.json, src/main/TopBanner.vue
#340
- 이벤트 링크 연결 및 검색 기능 수정
어떤 변경 사항이 있나요?
=> #340 메인 광고 베너 수정

src/events/EventHeaderInfo.vue
#329 
이벤트 상세에서 채팅방 이동 가능하도록 추가
어떤 변경 사항이 있나요?
=> [#329] 이벤트 상세 페이지에서 채팅방 버튼 추가

src/events/EventDetail.vue
=> #348 상세 페이지 내 배우 사진 수정

src/events/chat/Detail.vue, src/stores/useChatRoomStore.js
#353
프로필사진 미보유 사용자 이미지 깨지는 것, 색깔이 보이도록 수정함
어떤 변경 사항이 있나요?
=> [feat] 프로필사진 미보유 사용자 디자인 수정

src/events/chat/Detail.vue
null
젠킨스 쿠버네티스 배포 테스트
어떤 변경 사항이 있나요?
=> [refactor] 주석제거 + 젠킨스 테스트

src/events/EventDetail.vue
#358
- 상세 정보 줄바꿈
- 없는 정보 안 띄우기기
어떤 변경 사항이 있나요?
=> #358 공연 상세정보 수정

src/events/chat/Detail.vue, src/stores/useChatRoomStore.js
#364 
사이드바 채팅데이터 초기 로딩 - 내 메세지 구분 지연 오류 고치기
어떤 변경 사항이 있나요?
=> [fix] 내가 보낸 메세지 바로 반영되도록 수정

src/events/chat/Detail.vue
#369 
빈 메시지 전송 시도 시 발생하는 경고 수정
어떤 변경 사항이 있나요?
=> fix: 빈 메시지 전송 시도 시 발생하는 경고 수정 #369

src/common/Sidebar.vue, src/events/EventHeaderInfo.vue, src/events/chat/Detail.vue, src/events/chat/List.vue, src/stores/useChatRoomListStore.js, src/stores/useChatRoomStore.js
#373 #378
실시간 채팅방 이용자 수, 실시간 참여 목록 개선
어떤 변경 사항이 있나요?
확인 부탁드립니당..
=> Feat/chat/redis participant 실시간 채팅방 이용자 수, 실시간 참여 목록 개선

src/stores/useChatRoomStore.js
#380
내 메세지와 다른 사용자 메세지 구분하는 UI 오류 수정
어떤 변경 사항이 있나요?
=> [fix] 내 메세지 방향 디자인 오류 수정

src/common/Sidebar.vue, src/stores/useChatRoomStore.js
=> [#384] 웹소켓 분리

src/main/PopularPost.vue
메인페이지에서 게시글 눌렀을 때 조회수 증가
어떤 변경 사항이 있나요?
=> [feat] 메인페이지에서 게시글 조회수 증가

package-lock.json, package.json, src/stores/useChatRoomStore.js
#372
- **`useChatRoomStore.js`**의 `/topic/chat.room.likes.{roomId}` 콜백에서 `payload` 구조를 `{ roomIdx, heartCount }`로 파싱하여 UI 업데이트
-  `events/chat/Detail.vue` 채팅방에서 하트의 개수`heartCount`를 실시간으로 표시해주도록 UI 변경
어떤 변경 사항이 있나요?
=> [feat/chat/heart-redis] 하트 uuid 부여 Idempotent pattern 적용

src/common/Header.vue, src/user/Login.vue
=> [chore] 미사용 컴포넌트 가려두기
